name: Compile and publish TGE

on: [push]

jobs:
  processing3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Compile
        run: ./compile_tge.sh
        env:
          PROCESSING_VERSION: 3.5.4
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts 3
          path: jars-3.5.4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jars-3.5.4/*.jar
          name: For Processing 3 - ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}

  processing4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Compile
        run: ./compile_tge.sh
        env:
          PROCESSING_VERSION: 4.0.1
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts 4
          path: jars-4.0.1
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jars-4.0.1/*.jar
          name: For Processing 4 - ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
